package FastMediaInfo

type General struct {
	Type                     string `json:"@type"`
	Count                    string `json:"Count"`
	StreamCount              string `json:"StreamCount"`
	StreamKind               string `json:"StreamKind"`
	StreamKindString         string `json:"StreamKind_String"`
	StreamKindID             string `json:"StreamKindID"`
	VideoCount               string `json:"VideoCount"`
	AudioCount               string `json:"AudioCount"`
	VideoFormatList          string `json:"Video_Format_List"`
	VideoFormatWithHintList  string `json:"Video_Format_WithHint_List"`
	VideoCodecList           string `json:"Video_Codec_List"`
	AudioFormatList          string `json:"Audio_Format_List"`
	AudioFormatWithHintList  string `json:"Audio_Format_WithHint_List"`
	AudioCodecList           string `json:"Audio_Codec_List"`
	CompleteName             string `json:"CompleteName"`
	FolderName               string `json:"FolderName"`
	FileNameExtension        string `json:"FileNameExtension"`
	FileName                 string `json:"FileName"`
	FileExtension            string `json:"FileExtension"`
	Format                   string `json:"Format"`
	FormatString             string `json:"Format_String"`
	FormatExtensions         string `json:"Format_Extensions"`
	FormatCommercial         string `json:"Format_Commercial"`
	CodecID                  string `json:"CodecID"`
	FileSize                 string `json:"FileSize"`
	FileSizeString           string `json:"FileSize_String"`
	FileSizeString1          string `json:"FileSize_String1"`
	FileSizeString2          string `json:"FileSize_String2"`
	FileSizeString3          string `json:"FileSize_String3"`
	FileSizeString4          string `json:"FileSize_String4"`
	Duration                 string `json:"Duration"`
	DurationString           string `json:"Duration_String"`
	DurationString1          string `json:"Duration_String1"`
	DurationString2          string `json:"Duration_String2"`
	DurationString3          string `json:"Duration_String3"`
	DurationString4          string `json:"Duration_String4"`
	DurationString5          string `json:"Duration_String5"`
	OverallBitRate           string `json:"OverallBitRate"`
	OverallBitRateString     string `json:"OverallBitRate_String"`
	FrameRate                string `json:"FrameRate"`
	FrameRateString          string `json:"FrameRate_String"`
	FrameCount               string `json:"FrameCount"`
	StreamSize               string `json:"StreamSize"`
	StreamSizeString         string `json:"StreamSize_String"`
	StreamSizeString1        string `json:"StreamSize_String1"`
	StreamSizeString2        string `json:"StreamSize_String2"`
	StreamSizeString3        string `json:"StreamSize_String3"`
	StreamSizeString4        string `json:"StreamSize_String4"`
	StreamSizeString5        string `json:"StreamSize_String5"`
	StreamSizeProportion     string `json:"StreamSize_Proportion"`
	IsStreamable             string `json:"IsStreamable"`
	FileModifiedDate         string `json:"File_Modified_Date"`
	FileModifiedDateLocal    string `json:"File_Modified_Date_Local"`
	EncodedApplication       string `json:"Encoded_Application"`
	EncodedApplicationString string `json:"Encoded_Application_String"`
	FormatUrl                string `json:"Format_Url"`
	EncodedLibrary           string `json:"Encoded_Library"`
	EncodedLibraryString     string `json:"Encoded_Library_String"`
	Extra                    struct {
		SourceDelay           string `json:"Source_Delay"`
		SourceDelaySource     string `json:"Source_Delay_Source"`
		CodecConfigurationBox string `json:"CodecConfigurationBox"`
	} `json:"extra"`
}
