package FastMediaInfo

type Video struct {
	Type                           string `json:"@type"`
	Count                          string `json:"Count"`
	StreamCount                    string `json:"StreamCount"`
	StreamKind                     string `json:"StreamKind"`
	StreamKindString               string `json:"StreamKind_String"`
	StreamKindID                   string `json:"StreamKindID"`
	Format                         string `json:"Format"`
	FormatString                   string `json:"Format_String"`
	FormatCommercial               string `json:"Format_Commercial"`
	FormatProfile                  string `json:"Format_Profile"`
	InternetMediaType              string `json:"InternetMediaType"`
	CodecID                        string `json:"CodecID"`
	Duration                       string `json:"Duration"`
	DurationString                 string `json:"Duration_String"`
	DurationString1                string `json:"Duration_String1"`
	DurationString2                string `json:"Duration_String2"`
	DurationString3                string `json:"Duration_String3"`
	DurationString4                string `json:"Duration_String4"`
	DurationString5                string `json:"Duration_String5"`
	FrameRate                      string `json:"FrameRate"`
	FrameRateString                string `json:"FrameRate_String"`
	FrameCount                     string `json:"FrameCount"`
	StreamSize                     string `json:"StreamSize"`
	StreamSizeString               string `json:"StreamSize_String"`
	StreamSizeString1              string `json:"StreamSize_String1"`
	StreamSizeString2              string `json:"StreamSize_String2"`
	StreamSizeString3              string `json:"StreamSize_String3"`
	StreamSizeString4              string `json:"StreamSize_String4"`
	StreamSizeString5              string `json:"StreamSize_String5"`
	StreamSizeProportion           string `json:"StreamSize_Proportion"`
	StreamOrder                    string `json:"StreamOrder"`
	ID                             string `json:"ID"`
	IDString                       string `json:"ID_String"`
	FormatInfo                     string `json:"Format_Info"`
	FormatUrl                      string `json:"Format_Url"`
	FormatLevel                    string `json:"Format_Level"`
	Width                          string `json:"Width"`
	WidthString                    string `json:"Width_String"`
	Height                         string `json:"Height"`
	HeightString                   string `json:"Height_String"`
	SampledWidth                   string `json:"Sampled_Width"`
	SampledHeight                  string `json:"Sampled_Height"`
	PixelAspectRatio               string `json:"PixelAspectRatio"`
	DisplayAspectRatio             string `json:"DisplayAspectRatio"`
	DisplayAspectRatioString       string `json:"DisplayAspectRatio_String"`
	FrameRateMode                  string `json:"FrameRate_Mode"`
	FrameRateModeString            string `json:"FrameRate_Mode_String"`
	FrameRateNum                   string `json:"FrameRate_Num"`
	FrameRateDen                   string `json:"FrameRate_Den"`
	ColorSpace                     string `json:"ColorSpace"`
	ChromaSubsampling              string `json:"ChromaSubsampling"`
	ChromaSubsamplingString        string `json:"ChromaSubsampling_String"`
	BitDepth                       string `json:"BitDepth"`
	BitDepthString                 string `json:"BitDepth_String"`
	ColourDescriptionPresent       string `json:"colour_description_present"`
	ColourDescriptionPresentSource string `json:"colour_description_present_Source"`
	ColourRange                    string `json:"colour_range"`
	ColourRangeSource              string `json:"colour_range_Source"`
	ColourPrimaries                string `json:"colour_primaries"`
	ColourPrimariesSource          string `json:"colour_primaries_Source"`
	TransferCharacteristics        string `json:"transfer_characteristics"`
	TransferCharacteristicsSource  string `json:"transfer_characteristics_Source"`
	MatrixCoefficients             string `json:"matrix_coefficients"`
	MatrixCoefficientsSource       string `json:"matrix_coefficients_Source"`
	Extra                          struct {
		SourceDelay           string `json:"Source_Delay"`
		SourceDelaySource     string `json:"Source_Delay_Source"`
		CodecConfigurationBox string `json:"CodecConfigurationBox"`
	} `json:"extra"`
	Default       string `json:"Default"`
	DefaultString string `json:"Default_String"`
}
